# Generated by Django 4.1 on 2022-08-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="decription",
            new_name="description",
        ),
    ]
